<li><a href="/<?php if(!is_front_page() && $is_translated){echo $slug . '/';} ?>"><span>English</span></a></li>
<li><a href="/zh-hans/<?php if(!is_front_page() && $is_translated){echo $slug . '/';} ?>"><span>简体中文</span></a></li>
<li><a href="/fr/<?php if(!is_front_page() && $is_translated){echo $slug . '/';} ?>"><span>Français</span></a></li>
<li><a href="/de/<?php if(!is_front_page() && $is_translated){echo $slug . '/';} ?>"><span>Deutsch</span></a></li>
<li><a href="/id/<?php if(!is_front_page() && $is_translated){echo $slug . '/';} ?>"><span>Indonesia</span></a></li>
<li><a href="/pt-br/<?php if(!is_front_page() && $is_translated){echo $slug . '/';} ?>"><span>Português</span></a></li>
<li><a href="/ru/<?php if(!is_front_page() && $is_translated){echo $slug . '/';} ?>"><span>Русский</span></a></li>
<li><a href="/es/<?php if(!is_front_page() && $is_translated){echo $slug . '/';} ?>"><span>Español</span></a></li>
<li><a href="/tr/<?php if(!is_front_page() && $is_translated){echo $slug . '/';} ?>"><span>Türkçe</span></a></li>
<li><a href="/pl/<?php if(!is_front_page() && $is_translated){echo $slug . '/';} ?>"><span>polski</span></a></li>
<li><a href="/it/<?php if(!is_front_page() && $is_translated){echo $slug . '/';} ?>"><span>Italiano</span></a></li>
<li><a href="/uk/<?php if(!is_front_page() && $is_translated){echo $slug . '/';} ?>"><span>Українська</span></a></li>
<li><a href="/ar/<?php if(!is_front_page() && $is_translated){echo $slug . '/';} ?>"><span>العربية</span></a></li>
<li><a href="/vi/<?php if(!is_front_page() && $is_translated){echo $slug . '/';} ?>"><span>Tiếng Việt</span></a></li>